config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    get "/custom_sign_out" => "devise/sessions#destroy", as: :custom_destroy_user_session
  end

  root 'splash_screen#index'
  get '/splash_screen', to: 'splash_screen#index', as: 'splash_screen'
  resources :groups, only: [:index, :show, :new, :create] do
    resources :founds_drainers, only: [:new, :create]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Group do |group|
      group.user == user
    end
    can :manage, FoundsDrainer do |fd|
      fd.user == user
    end

    can :create, Group
    can :create, FoundsDrainer
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/founds_drainer.rb
class FoundsDrainer < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :author_id, presence: true

  validate :at_least_one_group

  private

  def at_least_one_group
    return if group_ids.empty?

    puts 'error while creating transaction'
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :founds_drainers

  validates :name, presence: true
  validates :icon, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :founds_drainers, foreign_key: :author_id
  has_many :groups

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/founds_drainers_controller.rb
class FoundsDrainersController < ApplicationController
  def new
    @group = Group.find(params[:group_id])
    @founds_drainer = FoundsDrainer.new
    authorize! :create, @founds_drainer
  end

  # POST /groups
  def create
    @group = Group.find(params[:group_id])
    @founds_drainer = FoundsDrainer.new(fd_params)
    @founds_drainer.author = current_user
    authorize! :new, @founds_drainer

    if @founds_drainer.save
      redirect_to group_path(@group), notice: 'Found drainer was successfully created.'
    else
      render :new
    end
  end

  private

  def fd_params
    params.require(:founds_drainer).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  def index
    @groups = current_user.groups
    @group_totals = {}

    @groups.each do |group|
      @group_totals[group.id] = group.founds_drainers.sum(:amount)
    end
  end

  def show
    @group = current_user.groups.includes(:founds_drainers).find(params[:id])
    @group_totals = @group.founds_drainers.sum(:amount)
  end

  def new
    @group = Group.new
  end

  # POST /groups
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/found_drainers_helper.rb
module FoundDrainersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/views/founds_drainers/new.html.erb
<%= render 'layouts/nav' %>

<%= form_with model: @founds_drainer, url: group_founds_drainers_path(@group) do |f| %>
  <div class="bg-white">
    <div class="field">
      <%= f.text_field :name, class: 'placeholder border-top-1', placeholder: "Name" %>
    </div>

    <div class="horizontal-line"></div>
  
    <div class="field">
      <%= f.number_field :amount, class: 'placeholder', placeholder: "Amount" %>
    </div>

    <div class="horizontal-line"></div>

    <div class="categories-cont dflex flexcol">
      <%= f.label :categories, "Select Categories", class: 'label2' %><br />
      <% current_user.groups.each do |category| %>
        <div class="dflex spacebetween">
          <%= check_box_tag 'founds_drainer[group_ids][]', category.id, false, id: "group_#{category.id}" %>
          <div class="label1"><%= category.name %></div>
        </div>
        <br />
      <% end %>
    </div>
    
  
    <div class="login-button-2">
      <%= f.submit "SAVE" %>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<%= render 'layouts/nav' %>

<div class="groups-cont dflex flexcol">
  <% @groups.each do |group| %>
    <%= link_to group_path(group), class: 'link-cont' do %>
      <div class="dflex">
        <div class="dflex small-img">
          <img src="<%= group.icon %>" alt="icon">
        </div>
        <div class="group-name">
          <%= group.name %>
        </div>
        <div class="group-total">
          $<%= @group_totals[group.id] %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>
<%= link_to new_group_path do %>
  <div class="bg-green add-group-cont dflex a-center j-center">
    <div class="link-to-new-group dflex a-center j-center">
      ADD NEW CATEGORY
    </div>
  </div>
<% end %>

app/views/groups/new.html.erb
<%= render 'layouts/nav' %>

<%= form_with model: @group do |f| %>
  <div class="bg-white">
    <div class="field">
      <%= f.text_field :name, class: 'placeholder border-top-1', placeholder: "Name" %>
    </div>

    <div class="horizontal-line"></div>

    <div class="field">
      <%= f.text_field :icon, class: 'placeholder border-bottom-1', placeholder: "Image Url" %>
    </div>

    <div class="login-button-2">
      <%= f.submit "SAVE" %>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<%= render 'layouts/nav' %>

<div class="transactions-cont dflex flexcol">
  <div class="group-cont">
    <div class="dflex bg-white space-between">
      <div class="dflex small-img">
        <img src="<%= @group.icon %>" alt="icon">
      </div>
      <div class="group-name">
        <%= @group.name %>
      </div>
      <div class="group-total">
        $<%= @group_totals %>
      </div>
    </div>
    <div class="horizontal-line2"></div>
    <% @group.founds_drainers.each do |drainer| %>
      <div class="drainer-cont dflex space-between">
        <p class="amount-name"><%= drainer.name %></p>
        <p class="amount"> $<%= drainer.amount %></p>
      </div>
      <div class="horizontal-line2"></div>
    <% end %>
  </div>
</div>

<%= link_to new_group_founds_drainer_path(@group) do %>
  <div class="bg-green add-group-cont dflex a-center j-center">
    <div class="link-to-new-group dflex a-center j-center">
      ADD NEW TRANSACTION
    </div>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<div class="dflex navbar a-center">
<% if (['sessions', 'passwords', 'registrations'].include?(controller_name) && action_name == 'new') || (controller_name == 'groups' && action_name == 'index') %>
    <%= link_to root_path do %>
      <%= image_tag('arrow-left.svg', alt: 'back', class: 'l-arrow') %>
    <% end %>
  <% else %>
    <%= link_to groups_path do %>
      <%= image_tag('arrow-left.svg', alt: 'back', class: 'l-arrow') %>
    <% end %>
  <% end %>
  <div class="title">
    <% if controller_name == 'groups' && action_name == 'index' %>
      CATEGORIES
    <% elsif controller_name == 'groups' && action_name == 'new' %>
      NEW CATEGORY
    <% elsif controller_name == 'groups' && action_name == 'show' %>
      TRANSACTIONS
    <% elsif controller_name == 'founds_drainer' && action_name == 'new' %>
      NEW TRANSACTION
    <% elsif controller_name == 'sessions' && action_name == 'new' %>
      LOG IN
    <% elsif controller_name == 'registrations' && action_name == 'new' %>
      REGISTER
    <% elsif controller_name == 'passwords' && action_name == 'new' %>
      FORGOT YOUR PASSWORD?
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WalletWatcher</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="alert-notice">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/splash_screen/index.html.erb
<div class="dflex flexcol a-center j-center cont1">
  <h1 class="courier-new big-logo dflex flexcol j-center">
    Wallet <br/> 
    Watcher
  </h1>
  <div class="buttons dflex flexcol j-center a-center">
    <% if user_signed_in? %>
      <%= link_to groups_path, class: 'button-cont' do %>
        <button class="login-button">CATEGORIES</button>
      <% end %>
      <%= link_to custom_destroy_user_session_path, class: 'button-cont' do %>
        <button class="signup-button">LOG OUT</button>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: 'button-cont' do %>
        <button class="login-button">LOG IN</button>
      <% end %>
      <%= link_to new_user_registration_path, class: 'button-cont' do %>
        <button class="signup-button">SIGN UP</button>
      <% end %>
    <% end %>
  </div>
</div>